### ISSUE TITLE
Question about the degree of synthetic vessel graph.

### ISSUE THREAD

**Issue by Tonniia** [jocpae/VesselGraph#20]
I take a look at ogbn-synthetic_graph_3_pb_minRadiusAvg dataset load from PygNodePropPredDataset, and find that the degree distribution is as follows:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/56153611/187389735-f0d11b47-a879-44de-b62c-97f6fe799cdd.png">
Most of the nodes have a degree of 2 and 4 (1533 and 1599). This does not follow the claim in the paper _Whole Brain Vessel Graphs: A Dataset and Benchmark for Graph Learning and Neuroscience (VesselGraph)_:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/56153611/187390243-dc229b0e-01bd-4e9a-bef2-67e2d0e2f4db.png">
I wonder if the 5 synthetic vessel graphs have the same properties as the real-world dataset.
Thanks in advance.

**Comment by jqmcginnis** [comment]
Hi @Sutongtong233,

thank you very much for your question and the interest in the paper and dataset. You are absolutely correct, the synthetic graphs do not follow the underlying distribution w.r.t node degree. We used these graphs to test the dataloaders and algorithms on smaller graphs when starting this project, and as far as I remember the graphs originate from _Matthias Schneider et al. Tissue metabolism driven arterial tree generation. Med Image Anal., 16(7):1397–1414, 2012._ 
We also did not intend the synthetic graphs to be identical, as we wanted to provide a very universal dataset to the community (by the way - dataset contributions are welcome! :slightly_smiling_face: ).

I believe the whole mouse brain graph features a lot more microvessels, unconnected vessels and vessels of higher degrees as well. If you want to test the impact of bulge size on the synthetic graphs as well, we can provide the segmentation mask and the [instructions](https://github.com/jqmcginnis/vessel_graph_pipeline) how to generate the graphs in case you would like to examine this!

Cheers,
Julian

**Comment by jqmcginnis** [comment]
By the way, we just released one of the whole graphs as [official OGB Graph](https://ogb.stanford.edu/docs/linkprop/#ogbl-vessel), and will advertise this in the Readme soon as well, just in case you are interested in link prediction and would like to test your algorithm and compare it to the [baselines](https://ogb.stanford.edu/docs/leader_linkprop/#ogbl-vessel).

**Comment by Tonniia** [comment]
Thanks a lot!
