### ISSUE TITLE
Dataset links expired

### ISSUE THREAD

**Issue by blukaz** [jocpae/VesselGraph#21]
Hi,

the provided links to the datasets (both the raw and preprocessed) are expired or not working. 
Could you please update them?
Thanks!

**Comment by jqmcginnis** [comment]
Hi @blukaz,

thank you very much for letting us know, could you please try again - I renewed all expiry dates (to my knowledge).
Also, feel free to check out our link prediction task, now officially part of [OGB ](https://ogb.stanford.edu/docs/leader_linkprop/#ogbl-vessel) as ogbl-vessel.

If it works, feel free to close this issue! :+1:

**Comment by blukaz** [comment]
Hi @jqmcginnis,

thank you! it works :)
