### ISSUE TITLE
Can your framework process the 2D vessel graph?

### ISSUE THREAD

**Issue by ZDstandup** [jocpae/VesselGraph#3]
Hi, can your framework process the 2D vessel graph?

**Comment by jqmcginnis** [comment]
Hi @ZDstandup,

all our segmentations of the whole mouse brain originate from 3D imaging methods and subsequently, we utilize the graph extraction algorithm by Drees et. al. to extract the 3D spatial graph and utilize this representation for all graph learning algorithms. 

In general, the processing of 2D vessel graphs is currently not supported by our dataset. Depending on which steps you would like to utilize, perhaps you can use some of the pipeline steps we implemented, for example the general concepts for link prediction and the dataset loaders. 

If you can provide some details what specifically you are interested in / looking for, I might be able to point you to other research in 2D vessel graphs that I know of :) 

Thanks again for your interest!

**Comment by ZDstandup** [comment]
Hi @jqmcginnis , thanks a lot for your detailed response to my question. I'm looking for some research about how to represent the vessel tree using a graph, such as the coronary artery in 2D angiography. Could you please point out some research you know of?
Thanks a lot again!

**Comment by jqmcginnis** [comment]
Hi @ZDstandup,

I discussed the matter with @jocpae and there might be multiple interesting things for you to check:

1) If you reshape your current segmentation (NxM) to (NxMx1) you could use our existing graph extraction algorithm by Drees et.al. and check if this new representation is insightful for you. For this, you can use the [Voreen Tool](https://www.uni-muenster.de/Voreen/) from University of Münster or look at the repository we used for the generation of our dataset c.f. [CustomRepo](https://github.com/jqmcginnis/voreen).

2) If you would like to look into 2D graph generation, perhaps the following papers and research is helpful:

-  Chapman, Brian E., Holly P. Berty, and Stuart L. Schulthies. "Automated generation of directed graphs from vascular segmentations." Journal of biomedical informatics 56 (2015): 395-405.

- Aanjaneya, Mridul, et al. "Metric graph reconstruction from noisy data." Proceedings of the twenty-seventh annual symposium on Computational geometry. 2011.

- Check these implementations on github:

  1. [Metric Graph Reconstruction](
  https://github.com/markolalovic/metric-graph-reconstruction)
  
  2. [Chapman et al.](https://github.com/chapmanbe/vasctree)

**Comment by ZDstandup** [comment]
Hi, @jqmcginnis 

Wow, your response helps me a lot. Many thanks for your kind response. Thank jocpae, too.
