### ISSUE TITLE
What is the usage of sample_data folder?

### ISSUE THREAD

**Issue by FeynmanDNA** [jocpae/VesselGraph#8]
`sample_data` folder and its csv and vtk files do not seem to be used anywhere in this repo or documented. May I know what do we need them for?

**Comment by FeynmanDNA** [comment]
It is also very big: `93M	./sample_data`
![image](https://user-images.githubusercontent.com/26617036/168472734-ce492cdc-52d3-41e3-8333-860da82bc9ca.png)

Maybe we can store these data outside of git?

**Comment by jqmcginnis** [comment]
@suprosanna @jocpae: I would be happy for your input here. Thanks!

**Comment by jocpae** [comment]
Good comment, please remove @jqmcginnis :)

**Comment by jqmcginnis** [comment]
Done!
