### ISSUE TITLE
Missing csv and Duplicate py file due to update_ogb*_master.sh

### ISSUE THREAD

**Issue by FeynmanDNA** [jocpae/VesselGraph#9]
Hi, as I was going through the steps in the instructions, I noticed two problems from this:
>please run `./source/ogb_dataset/link_prediction/update_ogbl_master.sh` and `./source/ogb_dataset/node_classification/update_ogbn_master.sh` once

In the `update_ogb*_master.sh` files:
```sh
python3 make_master_file.py
cp master.csv ../../ogb/linkproppred/master.csv
cp make_master_file.py ../../ogb/linkproppred/make_master_file.py
```

1. There are no `master.csv` files. Maybe it is better to mention in the README that `master.csv` will be generated somehow?
2. `make_master_file.py` is duplicated in the source and destination folders.

**Comment by jqmcginnis** [comment]
@FeynmanDNA thank you very much for the question. Before we address this in the Readme, could you kindly rephrase issue 2. I am not completely sure what you are referring to. Would you propose moving the file rather than copying it?

**Comment by FeynmanDNA** [comment]
hi for point 2, i meant the file `make_master_file.py` is copied and thus duplicated, but both copies are stored and git-tracked in the source and destination folders of the `cp` command

**Comment by jqmcginnis** [comment]
Hi @FeynmanDNA,

please review the proposed changes I made in PR #14 :)

Feel free to push changes to the branch, if you stumble upon any issue!

Cheers,
Julian

**Comment by FeynmanDNA** [comment]
@jqmcginnis Thank you very much for the fix!
